import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Layout from "@/components/Layout/Layout"

const alefba = localFont({
  src : "../../public/fonts/Far_Alphabet/Far_Alphabet.ttf"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        className={alefba.className}>
          <Layout> {children}</Layout>
       
      </body>
    </html>
  );
}
